dev-mode: true

logger:
  level: "debug" # Options: debug, info, warn, error, fatal
  pretty: true

http:
  port: 8080
  http_logs: true

# Database settings
database:
  dialect: sqlite # Options: sqlite, postgres
  dsn: "./database.db"

# Cache settings
caching:
  enabled: true
  type: memory # Options: memory, redis
  expire: 3600 # Cache expiration time in seconds

  # redis:
  #   addr: "localhost:6379"
  #   password: ""
  #   db: 0

  memory:
    size: 100 # Maximum number of items in memory cache

# Session settings
session:
  secret-key: "zotion-secret-key" # Secret key for session encryption
  issuer: "zotion" # Issuer for JWT tokens
  expire: 604800 # 7 days in seconds

auth:
  disable-admin-account: false

# Registration settings
registration:
  enabled: true
  require-email-verification: false
  domain-whitelist: []
  password-min-length: 12
  password-complexity: true