services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - 5432:5432
  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
